name: Build and Release MHTML Extractor Executables

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt5 PyQtWebEngine requests beautifulsoup4

      - name: Build macOS executable
        run: |
          pyinstaller --name=MHTMLExtractor \
                      --windowed \
                      --add-data="mhtml_parser.py:." \
                      --onefile \
                      mhtml_extractor_gui.py
        env:
          PYINSTALLER_NO_BUNDLE: 1

      - name: Create DMG
        run: |
          mkdir -p dmg-staging/MHTMLExtractor.app
          cp -R dist/MHTMLExtractor.app dmg-staging/
          hdiutil create -srcfolder dmg-staging -volname "MHTML Extractor" -format UDZO dist/MHTMLExtractor.dmg

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MHTMLExtractor-macos
          path: |
            dist/MHTMLExtractor.app
            dist/MHTMLExtractor.dmg

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt5 PyQtWebEngine requests beautifulsoup4

      - name: Build Windows executable
        run: |
          pyinstaller --name=MHTMLExtractor ^
                      --windowed ^
                      --add-data="mhtml_parser.py;." ^
                      --onefile ^
                      mhtml_extractor_gui.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: MHTMLExtractor-windows
          path: dist/MHTMLExtractor.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt5 PyQtWebEngine requests beautifulsoup4

      - name: Install system libraries for PyQt
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-x11-0 libxcb-randr0 libxcb-xtest0 libxcb-xinerama0 libxcb-shape0 libxcb-xfixes0

      - name: Build Linux executable
        run: |
          pyinstaller --name=MHTMLExtractor \
                      --add-data="mhtml_parser.py:." \
                      --onefile \
                      mhtml_extractor_gui.py

      - name: Make executable
        run: chmod +x dist/MHTMLExtractor

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: MHTMLExtractor-linux
          path: dist/MHTMLExtractor

  release:
    name: Publish GitHub Release
    needs: [build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: MHTMLExtractor-macos
          path: artifacts/

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: MHTMLExtractor-windows
          path: artifacts/

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: MHTMLExtractor-linux
          path: artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
